# Generated by Django 5.2 on 2025-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_internalmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmark',
            name='subject',
            field=models.CharField(choices=[('Mathematics I', 'Mathematics I'), ('Physics', 'Physics'), ('English for Technical Communication', 'English for Technical Communication'), ('Computer Programming', 'Computer Programming'), ('Fundamental of Computing Technology', 'Fundamental of Computing Technology'), ('Engineering Drawing I', 'Engineering Drawing I'), ('Workshop Technology', 'Workshop Technology')], max_length=100),
        ),
    ]
