# Generated by Django 5.1.2 on 2025-04-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rollno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
