# Generated by Django 5.2 on 2025-05-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineering_economics', models.IntegerField(default=0)),
                ('algorithm_analysis_and_design', models.IntegerField(default=0)),
                ('numerical_method', models.IntegerField(default=0)),
                ('research_methodology', models.IntegerField(default=0)),
                ('computer_architecture_and_design', models.IntegerField(default=0)),
                ('operating_system', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
