# Generated by Django 5.2 on 2025-05-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('theory_full_marks', models.PositiveIntegerField(default=0)),
                ('theory_pass_marks', models.PositiveIntegerField(default=0)),
                ('theory_obtained_marks', models.PositiveIntegerField(default=0)),
                ('practical_full_marks', models.PositiveIntegerField(default=0)),
                ('practical_pass_marks', models.PositiveIntegerField(default=0)),
                ('practical_obtained_marks', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
