# Generated by Django 5.2 on 2025-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_internalmark_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmark',
            name='semester',
            field=models.IntegerField(choices=[(1, '1 Semester'), (2, '2 Semester'), (3, '3 Semester'), (4, '4 Semester'), (5, '5 Semester'), (6, '6 Semester'), (7, '7 Semester'), (8, '8 Semester')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='subject',
            field=models.CharField(choices=[('Mathematics I', 'Mathematics I'), ('Physics', 'Physics'), ('English for Technical Communication', 'English for Technical Communication'), ('Computer Programming', 'Computer Programming'), ('Fundamental of Computing Technology', 'Fundamental of Computing Technology'), ('Engineering Drawing I', 'Engineering Drawing I'), ('Mathematics II', 'Mathematics II'), ('Chemistry', 'Chemistry'), ('Engineering Mechanics', 'Engineering Mechanics'), ('Engineering Drawing II', 'Engineering Drawing II'), ('Environmental Science', 'Environmental Science'), ('Workshop Practice', 'Workshop Practice'), ('Data Structures', 'Data Structures'), ('Database Management System', 'Database Management System'), ('Operating System', 'Operating System'), ('Computer Networks', 'Computer Networks'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning')], max_length=100),
        ),
    ]
